-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 14:34:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdhotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdhotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdhotel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bdhotel` ;

-- -----------------------------------------------------
-- Table `bdhotel`.`huesped`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`huesped` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(55) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `fecha_naciiento` DATETIME NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(150) NOT NULL,
  `tipo_documento` VARCHAR(100) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `procedencia` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`estancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`estancia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_huesped` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `estado_estancia` VARCHAR(50) NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  `estado` TINYINT GENERATED ALWAYS AS (_utf8mb3'1') VIRTUAL,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_estancia_huesped1_idx` (`id_huesped` ASC) VISIBLE,
  INDEX `fk_estancia_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_estancia_huesped1`
    FOREIGN KEY (`id_huesped`)
    REFERENCES `bdhotel`.`huesped` (`id`),
  CONSTRAINT `fk_estancia_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdhotel`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdhotel`.`cobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`cobros` (
  `id` INT NOT NULL,
  `id_estancia` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `monto` DECIMAL(8,2) NOT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  `tipo_cobro` VARCHAR(45) NOT NULL,
  `detalle_cobro` VARCHAR(255) NULL DEFAULT NULL,
  `estado_cobro` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cobros_estancia1_idx` (`id_estancia` ASC) VISIBLE,
  CONSTRAINT `fk_cobros_estancia1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `bdhotel`.`estancia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdhotel`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precio_compra` DECIMAL(7,2) NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  `stock` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdhotel`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estancia` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_estancia` (`id_estancia` ASC) VISIBLE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `bdhotel`.`estancia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdhotel`.`detalle_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`detalle_producto` (
  `id_producto` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`, `id_venta`),
  INDEX `id_venta` (`id_venta` ASC) VISIBLE,
  CONSTRAINT `detalle_producto_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bdhotel`.`producto` (`id`),
  CONSTRAINT `detalle_producto_ibfk_2`
    FOREIGN KEY (`id_venta`)
    REFERENCES `bdhotel`.`venta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdhotel`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`habitacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estancia` INT NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `precio` DECIMAL(8,2) NOT NULL,
  `piso` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_habitacion_estancia1_idx` (`id_estancia` ASC) VISIBLE,
  CONSTRAINT `fk_habitacion_estancia1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `bdhotel`.`estancia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
