-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 12:31:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdhotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdhotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdhotel` DEFAULT CHARACTER SET utf8mb3 ;
USE `bdhotel` ;

-- -----------------------------------------------------
-- Table `bdhotel`.`huesped`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`huesped` (
  `idhuesped` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `edad` DATETIME NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `profesion_ocupacion` VARCHAR(150) NOT NULL,
  `tipo_documento` VARCHAR(100) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `procedencia` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idhuesped`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`habitacion` (
  `idhabitacion` INT NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `precio_diario` DECIMAL(5,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idhabitacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`estancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`estancia` (
  `idestancia` INT NOT NULL,
  `huesped_idhuesped` INT NOT NULL,
  `habitacion_idhabitacion` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `costo_hospedaje` DECIMAL NOT NULL,
  `estado` TINYINT NOT NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `fecha_actualizacion` VARCHAR(45) NULL,
  `reserva` VARCHAR(45) NULL,
  `penalidad` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `adelanto` INT NULL,
  PRIMARY KEY (`idestancia`),
  INDEX `fk_estancia_huesped1_idx` (`huesped_idhuesped` ASC) VISIBLE,
  INDEX `fk_estancia_habitacion1_idx` (`habitacion_idhabitacion` ASC) VISIBLE,
  CONSTRAINT `fk_estancia_huesped1`
    FOREIGN KEY (`huesped_idhuesped`)
    REFERENCES `bdhotel`.`huesped` (`idhuesped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estancia_habitacion1`
    FOREIGN KEY (`habitacion_idhabitacion`)
    REFERENCES `bdhotel`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdhotel`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `tipo_comprobate` VARCHAR(25) NOT NULL,
  `numero_comprobante` VARCHAR(25) NOT NULL,
  `total_pagado` DECIMAL(7,2) NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `estado` TINYINT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(7,2) NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `estancia_idestancia` INT NOT NULL,
  `pago_idpago` INT NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_estancia1_idx` (`estancia_idestancia` ASC) VISIBLE,
  INDEX `fk_consumo_pago1_idx` (`pago_idpago` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_estancia1`
    FOREIGN KEY (`estancia_idestancia`)
    REFERENCES `bdhotel`.`estancia` (`idestancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_pago1`
    FOREIGN KEY (`pago_idpago`)
    REFERENCES `bdhotel`.`pago` (`idpago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `unidad_medida` VARCHAR(25) NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `telefono` INT NOT NULL,
  `sueldo` DECIMAL(5,2) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT NOT NULL,
  `huesped_idhuesped` INT NOT NULL,
  `habitacion_idhabitacion` INT NOT NULL,
  `fecha_reserva` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_reserva_huesped1_idx` (`huesped_idhuesped` ASC) VISIBLE,
  INDEX `fk_reserva_habitacion1_idx` (`habitacion_idhabitacion` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bdhotel`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_huesped1`
    FOREIGN KEY (`huesped_idhuesped`)
    REFERENCES `bdhotel`.`huesped` (`idhuesped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_habitacion1`
    FOREIGN KEY (`habitacion_idhabitacion`)
    REFERENCES `bdhotel`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdhotel`.`tipo_habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`tipo_habitacion` (
  `descripcion` VARCHAR(150) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NOT NULL,
  `habitacion_idhabitacion` INT NOT NULL,
  INDEX `fk_tipo_habitacion_habitacion1_idx` (`habitacion_idhabitacion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_habitacion_habitacion1`
    FOREIGN KEY (`habitacion_idhabitacion`)
    REFERENCES `bdhotel`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdhotel`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdhotel`.`detalle` (
  `consumo_idconsumo` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`consumo_idconsumo`, `producto_idproducto`),
  INDEX `fk_detalle_consumo1_idx` (`consumo_idconsumo` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `bdhotel`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_consumo1`
    FOREIGN KEY (`consumo_idconsumo`)
    REFERENCES `bdhotel`.`consumo` (`idconsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
